# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

[![Travis-CI Build Status](https://travis-ci.org/ehsan66/emoptim.svg?branch=master)](https://travis-ci.org/ehsan66/emoptim)
