// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// update_nbest
List update_nbest(const NumericMatrix eucdist, const NumericMatrix pbest, const NumericMatrix nbest, const NumericVector pbestval, const NumericVector nbestval, const double sf);
RcppExport SEXP emoptim_update_nbest(SEXP eucdistSEXP, SEXP pbestSEXP, SEXP nbestSEXP, SEXP pbestvalSEXP, SEXP nbestvalSEXP, SEXP sfSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericMatrix >::type eucdist(eucdistSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type pbest(pbestSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type nbest(nbestSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type pbestval(pbestvalSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type nbestval(nbestvalSEXP);
    Rcpp::traits::input_parameter< const double >::type sf(sfSEXP);
    __result = Rcpp::wrap(update_nbest(eucdist, pbest, nbest, pbestval, nbestval, sf));
    return __result;
END_RCPP
}
