# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp evalCpp
#' @useDynLib emoptim
update_nbest <- function(eucdist, pbest, nbest, pbestval, nbestval, sf) {
    .Call('emoptim_update_nbest', PACKAGE = 'emoptim', eucdist, pbest, nbest, pbestval, nbestval, sf)
}

